#pragma once
#include "./common.h"

// ============================================================

#define SE_PRIVILEGE_DISABLED 0x0
#define SE_PRIVILEGE_ENABLED 0x1

#define SE_SID_ENABLED 0x1
#define SE_SID_DIABLED 0x0
#define SE_SID_DENY_ONLY 0x2
#define SE_SID_USER 0x10
#define SE_SID_GROUP 0x20

#define SE_ACCOUNT_TYPE_USER SE_SID_USER 
#define SE_ACCOUNT_TYPE_GROUP SE_SID_GROUP 
#define SE_ACCOUNT_TYPE_COMPUTER 0x30
#define SE_ACCOUNT_TYPE_WELLKNOWN 0x40
#define SE_ACCOUNT_TYPE_SERVICE 0x50

#define SE_ACE_TYPE_ALLOW 0x1
#define SE_ACE_TYPE_DENY 0x0
#define SE_ACE_TYPE_SUCCESS_AUDIT 0x2
#define SE_ACE_TYPE_FAILURE_AUDIT 0x3
#define SE_ACE_TYPE_MIX_AUDIT 0x4

#define SE_ACL_TYPE_DISCRITIONARY 0x0
#define SE_ACL_TYPE_SECURITY 0x1

#define SE_UNTRUSTED_INTEGRITY_LEVEL 0x1000
#define SE_LOW_INTEGRITY_LEVEL 0x2000
#define SE_MEDIUM_INTEGRITY_LEVEL 0x3000
#define SE_HIGH_INTEGRITY_LEVEL 0x4000
#define SE_SYSTEM_INTEGRITY_LEVEL 0x5000

#define SE_SECURITY_DESCRIPTOR_SELF_RELATIVE_FROMAT 0x6000
#define SE_SECURITY_DESCRIPTOR_ABSOLUTE_FROMAT 0x7000

#define SE_WRITE_ALLOWED_FOR_LOWER_INTEGRITY_LEVELS 0x10000

#define SE_SECURITY_NULL_SID_AUTHORITY 0x1
#define SE_SECURITY_WORLD_SID_AUTHORITY 0x2
#define SE_SECURITY_LOCAL_SID_AUTHORITY 0x3
#define SE_SECURITY_CREATOR_SID_AUTHORITY 0x4
#define SE_SECURITY_NON_UNIQUE_AUTHORITY 0x5
#define SE_SECURITY_NT_AUTHORITY 0x6
#define SE_SECURITY_RESOURCE_MANAGER_AUTHORITY 0x7

#define SE_PRIMARY_ACCESS_TOKEN 0x30000
#define SE_IMPERSONATION_ACCESS_TOKEN 0x40000

#define SE_ANONYMOUS_IMPERSONATION_LEVEL 0x0
#define SE_IDENTIFICATION_IMPERSONATION_LEVEL 0x1
#define SE_IMPERSONATION_IMPERSONATION_LEVEL 0x2
#define SE_DELEGATION_IMPERSONATION_LEVEL 0x3
#define SE_INVALID_IMPERSONATION_LEVEL 0xFFFFFFFF

#define SE_OPENED 0x6000
#define SE_CREATED 0x7000

#define SE_SECURITY_DESCRIPTOR_FLAG_DACL_PRESENT 0x1
#define SE_SECURITY_DESCRIPTOR_FLAG_SACL_PRESENT 0x10
#define SE_SECURITY_DESCRIPTOR_FLAG_OWNER_PRESENT 0x100
#define SE_SECURITY_DESCRIPTOR_FLAG_GROUP_PRESENT 0x1000

#define SE_COMMON_RIGHTS (DELETE | SYNCHRONIZE | READ_CONTROL | WRITE_DAC | WRITE_OWNER | ACCESS_SYSTEM_SECURITY)

#define WXSTATUS_ACCESS_CHECK_SUCCEEDED WXSTATUS_SUCCESS
#define WXSTATUS_ACCESS_CHECK_FAILED WXSTATUS_FAILED

// =============================================================

typedef struct _HASHED_PASSWORD {
	ULONG size;
} HASHED_PASSWORD, *PHASHED_PASSWORD, *LPHASHED_PASSWORD;
typedef struct _WX_LUID {
	LONG low_part, high_part;
} WX_LUID, * PWX_LUID, * LPWX_LUID;
typedef struct _WX_INTEGRITY_LEVEL {
	WORD level;
	DWORD control_policies;
} WX_INTEGRITY_LEVEL, * PWX_INTEGRITY_LEVEL, * LPWX_INTEGRITY_LEVEL;
typedef struct _WX_PRIVILEGE {
	WX_LUID id;
	WORD attributes;
	UNICODE_STRING name;
	WX_LIST_ENTRY link;
	CRITICAL_SECTION lock;
} WX_PRIVILEGE, * PWX_PRIVILEGE, * LPWX_PRIVILEGE;
typedef struct _WX_SID {
	WX_LUID id;
	WX_SECRURITY_AUTHORITY auth;
	DWORD attributes;
	WX_LIST_ENTRY link;
	CRITICAL_SECTION lock;
} WX_SID, * PWX_SID, * LPWX_SID;
typedef struct _WX_ACCESS_CONTROL_ENTRY {
	BYTE type;
	LPWX_SID trustee;
	WX_ACCESS_MASK access_rights;
	WX_LIST_ENTRY link;
	CRITICAL_SECTION lock;
} WX_ACCESS_CONTROL_ENTRY, * PWX_ACCESS_CONTROL_ENTRY, * LPWX_ACCESS_CONTROL_ENTRY;
typedef struct _WX_ACCESS_CONTROL_LIST {
	BYTE type;
	union {
		struct {
			WX_LIST_ENTRY allow_ace_list_head;
			WX_LIST_ENTRY deny_ace_list_head;
		};
		struct {
			WX_LIST_ENTRY success_audit_ace_list_head;
			WX_LIST_ENTRY failure_audit_ace_list_head;
			WX_LIST_ENTRY mix_audit_ace_list_head;
		};
	};
	CRITICAL_SECTION lock;
} WX_ACCESS_CONTROL_LIST, * PWX_ACCESS_CONTROL_LIST, * LPWX_ACCESS_CONTROL_LIST;
typedef struct _WX_SECURITY_DESCRIPTOR {
	WORD format;
	ULONG flags;
	WX_INTEGRITY_LEVEL integrity_level;
	union {
		struct {
			LPWX_SID owner, group;
			LPWX_ACCESS_CONTROL_LIST acls[0x2];
		};
		struct {
			WX_SID _owner, _group;
			WX_ACCESS_CONTROL_LIST _acls[0x2];
		};
	};
	CRITICAL_SECTION lock;
} WX_SECURITY_DESCRIPTOR, * PWX_SECURITY_DESCRIPTOR, * LPWX_SECURITY_DESCRIPTOR;
typedef struct _WX_ACCOUNT {
	BYTE type;
	LPWX_SID sid;
	WX_INTEGRITY_LEVEL integrity_level;
	UNICODE_STRING name;
	LPHASHED_PASSWORD pwd;
	WX_LIST_ENTRY link, group_list_head, privilege_list_head;
	CRITICAL_SECTION lock;
} WX_ACCOUNT, * PWX_ACCOUNT, * LPWX_ACCOUNT;
typedef struct _WX_ACCESS_TOKEN {
	ULONG type;
	WX_IMPERSONATION_LEVEL impersonation_level;
	LPWX_SID user, default_owner, default_group;
	WX_INTEGRITY_LEVEL integrity_level;
	ULONG privileges_count;
	WX_LIST_ENTRY privilege_list_head, group_list_head;
	CRITICAL_SECTION lock;
	PWX_ACCESS_CONTROL_LIST default_dacl;
	WX_LIST_ENTRY restricted_sid_list_head;
} WX_ACCESS_TOKEN, * PWX_ACCESS_TOKEN, * LPWX_ACCESS_TOKEN;
typedef struct _WX_SECURITY_ACCOUNT_MANAGER_DATABASE {
	ULONG accounts_count;
	WX_LIST_ENTRY account_list_head;
	CRITICAL_SECTION lock;
} WX_SECURITY_ACCOUNT_MANAGER_DATABASE, * PWX_SECURITY_ACCOUNT_MANAGER_DATABASE, * LPWX_SECURITY_ACCOUNT_MANAGER_DATABASE;
typedef struct _WX_SECURITY_REFERENCE_MONITOR {
	LPWX_SECURITY_ACCOUNT_MANAGER_DATABASE sam_database;
	CRITICAL_SECTION lock;
	WX_LUID __next_luid[0x2];
	WX_LIST_ENTRY valid_privileges;
} WX_SECURITY_REFERENCE_MONITOR, *PWX_SECURITY_REFERENCE_MONITOR, *LPWX_SECURITY_REFERENCE_MONITOR;

// ==============================================================

// SRM functions
WXSTATUS __stdcall SeInitializeWxSecurityReferenceMonitor();
WXSTATUS __stdcall SeCreatePrivilege(LPCWSTR, ULONG, DWORD, LPWX_PRIVILEGE*, ULONG*);
WXSTATUS __stdcall SeAllocateAndInitializeSid(WX_SECRURITY_AUTHORITY, DWORD, LPWX_SID*);
WXSTATUS __stdcall SeCreateAccount(WX_SECRURITY_AUTHORITY, LPCWSTR, ULONG, LPBYTE, ULONG, ULONG, LPWX_ACCOUNT*, ULONG, LPCWSTR*, ULONG, ULONG, LPWX_ACCOUNT*, ULONG*);
WXSTATUS __stdcall SeAllocateAndInitializeAccessToken(LPWX_ACCOUNT, ULONG, WX_IMPERSONATION_LEVEL, LPWX_SID, LPWX_SID, LPWX_ACCESS_TOKEN*);
WXSTATUS __stdcall SeAllocateAndIitializeAcl(ULONG, LPWX_ACCESS_CONTROL_LIST*);
WXSTATUS __stdcall SeAddAceToAcl(LPWX_ACCESS_CONTROL_LIST, ULONG, LPWX_SID, WX_ACCESS_MASK);
WXSTATUS __stdcall SeGetAceAt(LPWX_ACCESS_CONTROL_LIST, LONG, ULONG, LPWX_ACCESS_CONTROL_ENTRY*);
WXSTATUS __stdcall SeRemoveAceFromAcl(LPWX_ACCESS_CONTROL_LIST, LONG, ULONG, LPWX_ACCESS_CONTROL_ENTRY*);
WXSTATUS __stdcall SeAllocateAndInitializeSecurityDescriptor(LPWX_ACCESS_TOKEN, WORD, ULONG, LPWX_SID, LPWX_SID, LPWX_ACCESS_CONTROL_LIST, LPWX_ACCESS_CONTROL_LIST, LPWX_SECURITY_DESCRIPTOR*);
WXSTATUS __stdcall SeSetSecurityDescriptorAcl(PWX_SECURITY_DESCRIPTOR, LPWX_ACCESS_CONTROL_LIST, PWX_ACCESS_CONTROL_LIST);
WXSTATUS __stdcall SeAccessCheck(PWX_ACCESS_TOKEN, LPVOID, WX_ACCESS_MASK, WX_ACCESS_MASK*);
WXSTATUS __stdcall SePrivilegeCheck(PWX_ACCESS_TOKEN, LPWX_PRIVILEGE*, ULONG);
WXSTATUS __stdcall SeLogonUser(LPCWSTR, ULONG, LPBYTE, ULONG, LPWX_ACCESS_TOKEN*);
WXSTATUS __stdcall SeSelfRelativeToAbsoluteSd(LPWX_SECURITY_DESCRIPTOR);
WXSTATUS __stdcall SeAbsoluteToSelfRelativeSd(LPWX_SECURITY_DESCRIPTOR);
WXSTATUS __stdcall SeAccessTokenMapGenericAccessRights(LPOBJECT_HEADER, WX_ACCESS_MASK, WX_ACCESS_MASK*);
WXSTATUS __stdcall SeLookupAccountByName(LPCWSTR, ULONG, LPWX_ACCOUNT*);
WXSTATUS __stdcall SeDuplicateSid(LPWX_SID, LPWX_SID*);
WXSTATUS __stdcall SeCreateRestrictedAccessToken(PWX_ACCESS_TOKEN, LPWX_SID*, ULONG, LPWX_ACCESS_TOKEN*);

// helpers
BOOLEAN __stdcall SeIsValidAccountName(LPCWSTR, ULONG);
WXSTATUS __stdcall SeLookupAccountBySid(LPWX_SID, LPWX_ACCOUNT*);
WXSTATUS __stdcall SeDuplicateAcl(LPWX_ACCESS_CONTROL_LIST, LPWX_ACCESS_CONTROL_LIST);
WXSTATUS __stdcall SeIsAceAppliable(LPWX_ACCESS_TOKEN, LPWX_ACCESS_CONTROL_ENTRY, LPWX_SID*);
BOOLEAN __stdcall SeCompareLuid(WX_LUID, WX_LUID);

// ==============================================================

WX_SECURITY_REFERENCE_MONITOR srm_manager = { 0x0 };
LPWX_ACCESS_TOKEN default_access_token = 0x0;
LPCWSTR computer_name = L"YOUR_COMPUTER_NAME", default_user_name = L"YOUR_USER_NAME";

// ==============================================================